lora:
  bias: none
  fan_in_fan_out: false
  inference_mode: false
  init_lora_weights: true
  lora_alpha: 32
  lora_dropout: 0.1
  modules_to_save: []
  r: 16
  revision: main
  target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
  task_type: CAUSAL_LM
  use_dora: false
  use_rslora: false
